spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: devconf5296@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true